mysql: 
  host: "localhost"
  port: "3306"
  database: "fulltext_search"
  username: "root"
  password: "root"

postgres: 
  host: "localhost"
  port: "5432"
  database: "fulltext_search"
  username: "postgres"
  password: "postgres"